# Docker Compose file to set up PostgreSQL and Redis services for the application.
# It is needed for local development and testing.
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # For initial setup scripts
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  pgdata:
