# Nodeport Service for miniconcurexpense application (simple local access)
apiVersion: v1
kind: Service
metadata:
  name: miniconcurexpense
  namespace: miniconcur
spec:
  type: NodePort
  selector:
    app: miniconcurexpense
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
