server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb  # match docker-compose
    username: app
    password: secret
  
  jpa:
    hibernate:
      ddl-auto: none  # Let Flyway handle schema creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[show_sql]": true  # Optional: for debugging
        "[format_sql]": true  # Optional: for debugging
  
  flyway:
    enabled: false  # We handle migrations manually per tenant
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: redis-service
      port: 6379

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.probes.enabled: true